### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by priyadarsh** [beejjacobs/node-samsung-remote#2]
Hi
I am getting the below error when starting this app after cloning
node index.js

class SamsungRemote {
^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by beejjacobs** [comment]
Hi,

What version of Node are you running? I am using v5.3.0; cloning it and running `node index.js` outputs nothing for me as expected.

**Comment by priyadarsh** [comment]
My bad I am using older version of node. After upgrading node index.js is not throwing any error. I am still  working on using it. Thanks a lot.

**Comment by beejjacobs** [comment]
No problem if you need any help drop me a message.
